export const FotosRetrato = [
  {
    alt: "retratoPeru_01",
    src: "../Imagenes/Retrato/comunidadAyacusa_11.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_02",
    src: "../Imagenes/Retrato/comunidadAyacusa_10.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_03",
    src: "../Imagenes/Retrato/ViajeIquitos_Loreto_06.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_04",
    src: "../Imagenes/Retrato/Nazca_47.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_05",
    src: "../Imagenes/Retrato/peru_Qòllority_42.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_06",
    src: "../Imagenes/Retrato/peru_paucartambo_35.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_07",
    src: "../Imagenes/Retrato/Cuzco_002.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_08",
    src: "../Imagenes/Retrato/Julio.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_09",
    src: "../Imagenes/Retrato/.Huaraz_04.jpg",
    width: 4,
    height: 3,
  },

  {
    alt: "retratoPeru_10",
    src: "../Imagenes/Retrato/0051ComunidadSoledad.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_11",
    src: "../Imagenes/Retrato/0061ComunidadSoledad.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_12",
    src: "../Imagenes/Retrato/Asaincas_13.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_13",
    src: "../Imagenes/Retrato/CuentaSantiago_23.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_14",
    src: "../Imagenes/Retrato/SegundaComunidad_06.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_15",
    src: "../Imagenes/Retrato/comunidadAyacusa_12.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_16",
    src: "../Imagenes/Retrato/comunidadAyacusa_13.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_17",
    src: "../Imagenes/Retrato/comunidadAyacusa_15.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_18",
    src: "../Imagenes/Retrato/comunidadAyacusa_59.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_19",
    src: "../imagenes/Retrato/0065ComunidadSoledad.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_20",
    src: "../Imagenes/Retrato/CatarataGocta_29.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_21",
    src: "../Imagenes/Retrato/VillaGonzalo_26.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_22",
    src: "../Imagenes/Retrato/Pescapaixe_ElDorado._4.jpg",
    width: 3,
    height: 4,
  },
  {
    alt: "retratoPeru_23",
    src: "../Imagenes/Retrato/comunidadAyacusa_8.jpg",
    width: 4,
    height: 3,
  },
  {
    alt: "retratoPeru_24",
    src: "../Imagenes/Retrato/comunidadAyacusa_7.jpg",
    width: 3,
    height: 4,
  },
];
